name: Deploy Resume Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Upload to Azure Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch \
            --account-name kwazstorageacct \
            --auth-mode key \
            --destination '$web' \
            --source . \
            --pattern "*.html" \
            --overwrite
          
          az storage blob upload-batch \
            --account-name kwazstorageacct \
            --auth-mode key \
            --destination '$web' \
            --source . \
            --pattern "*.css" \
            --overwrite
            
    - name: Purge CDN Cache
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az cdn endpoint purge \
            --content-paths "/*" \
            --profile-name kwaz-resume-cdn-profile \
            --name kwaz-resume-cdn-endpoint \
            --resource-group rg-cloud-resume-challenge
